CREATE TABLE "DLH_PORTAL_STATE" (
    "id" UUID NOT NULL,
    "dinas_id" UUID NOT NULL,
    "data" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DLH_PORTAL_STATE_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "DLH_PORTAL_STATE_dinas_id_key" ON "DLH_PORTAL_STATE"("dinas_id");

ALTER TABLE "DLH_PORTAL_STATE"
ADD CONSTRAINT "DLH_PORTAL_STATE_dinas_id_fkey"
FOREIGN KEY ("dinas_id") REFERENCES "DINAS"("id")
ON DELETE CASCADE ON UPDATE CASCADE;
