import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { ClientLayout } from "@/components/client-layout";
import { Toaster } from "sonner";
import "./globals.css";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${manrope.className} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <ClientLayout>{children}</ClientLayout>
                <Toaster position="top-center" richColors />
            </body>
        </html>
    );
}
