export const REDEMPTION_CONFIG = {
  MAX_QUANTITY_PER_TRANSACTION: 10,
  REDEMPTION_EXPIRY_MINUTES: parseInt(
    process.env.REDEMPTION_EXPIRY_MINUTES ?? "10",
    10,
  ),
  MAX_RETRY_ON_CONFLICT: 3,
  TOKEN_BYTE_LENGTH: 32,
  TOKEN_HINT_LENGTH: 6,
  TOKEN_HASH_ALGORITHM: "sha256" as const,
  TOKEN_HASH_ENCODING: "hex" as const,
  TOKEN_ENCODING: "base64url" as const,
  MAX_TOKEN_LENGTH: 256,
} as const;
